<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ApiToken;
use AppBundle\Entity\User;

/**
 * ApiTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiTokenRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByToken($token)
    {
        return $this->findOneBy(['token' => $token]);
    }

    /**
     * @param  User   $user
     * @return ApiToken[]
     */
    public function findAllForUser(User $user)
    {
        return $this->findBy(['user' => $user->getId()]);
    }
}
