<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Programmer;
use AppBundle\Entity\User;

/**
 * ProgrammerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammerRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param  User   $user
     * @return Programmer[]
     */
    public function findAllforUser(User $user)
    {
        return $this->findBy(['user' => $user]);
    }

    /**
     * @param $nickname
     * @return Programmer
     */
    public function findOneByNickname($nickname)
    {
        return $this->findOneBy(['nickname' => $nickname]);
    }
}
