<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Project;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param  $name
     * @return Project
     */
    public function findOneByName($name)
    {
        return $this->findOneBy(['name' => $name]);
    }

    /**
     * @param  $limit
     * @return Project[]
     */
    public function findRandom($limit)
    {
        $projects = $this->createQueryBuilder('p')
            ->setMaxResults($limit)
            ->getQuery()
            ->execute();

        shuffle($projects);

        return array_slice($projects, 0, $limit);
    }
}
